### ISSUE TITLE
mkdir: ../.git: No such file or directory

### ISSUE THREAD

**Issue by wangxiaobupt** [zangqilong198812/InitializeAppShell#2]
安装homebrew
已经安装homebrew
安装clang-format
已经安装clang-format
正在下载clang style 文件
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2259  100  2259    0     0    885      0  0:00:02  0:00:02 --:--:--   885
安装git flow
已经安装git flow
安装Git hook
mkdir: ../.git: No such file or directory
下载pre-commit文件
prepare.sh: line 42: ../.git/hooks/pre-commit: No such file or directory
chmod: ../.git/hooks/pre-commit: No such file or directory
设置gitattributes

**Comment by zangqilong198812** [comment]
这个是项目文件里没有.git文件夹。你这个项目有git么？

**Comment by wangxiaobupt** [comment]
谢谢，当时发现到问题了，已经解决了
